<?php
/**
 * Implementation of hook_block_info().
 */
function exp_sp_mobile_app_block_info() {
	try{
  $blocks = array();
  $blocks['mobileapp'] = array(
    'info' => t('mobileapp'),
  	'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => 'learning/mobile-app
    *'
  );

  return $blocks;
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_mobile_app_block_info', $ex);
  	expertusErrorThrow($ex);
  }
}



/**
 * Implementation of hook_menu().
 */
function exp_sp_mobile_app_menu($delta = '') {
  try{
  $items = array();
  $items['learning/mobile-app'] = array(
	  'title' => 'mobileapp',
	  'page callback' => 'empty_value',
	  'access arguments' => array('access content'),
	  //'access callback' => array(''),
	  'type' => MENU_CALLBACK
  );

/* Ctool popup */
  $items['learning/mobile-app/ctool-js/%'] = array (
    'title' => 'android',
    'page callback' => 'render_mobileapp_ctools_modal',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_mobile_app.inc'
  );
  
  $items['ajax/send-mobile-app-link/%/%'] = array (
    'title' => 'Send mobile app link',
    'page callback' => 'sendMobileAppLink',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_mobile_app.inc'
  );
  
  return $items;
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_mobile_app_menu', $ex);
  	expertusErrorThrow($ex);
  }
}


/**
 * Implements hook_theme().
 */
function exp_sp_mobile_app_theme() {
try {
  $themes = array();
  
  $themes['mobile_app_popup'] = array (
    'variables' => array('type' => ''),   
    'template' => 'exp_sp_mobile_app_template',
  );  

  return $themes;
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_mobile_app_theme', $ex);
  	expertusErrorThrow($ex);
  }
}


/**
 * Implements hook_block_view().
 */
function exp_sp_mobile_app_block_view($delta = '') {
  global $user;
  
  $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
  $css_module_optional = array('type' => 'file', 'group' => CSS_DEFAULT);
  
  try{
	  $block = array();
	  switch ($delta) {
	    case 'mobileapp':
	      include_once 'exp_sp_mobile_app.inc';
	      drupal_add_css(drupal_get_path('module', 'exp_sp_mobile_app').'/exp_sp_mobile_app.css', $css_module_optional);
	      drupal_add_js(drupal_get_path('module', 'exp_sp_mobile_app').'/exp_sp_mobile_app.js',$js_module_optional);
	      includeJqGridJsCss();

/*	      $block['blockname'] = "mobileapp";
	      $block['results'] = 'sdfdsfsd';
*/
	      
	      $block['subject'] = t('LBL962');
	      $block['content'] =  " ";
	      break;
	  }
  return $block;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_mobile_app_block_view', $ex);
    expertusErrorThrow($ex);
  } 
  
}


?>