<?php
function exp_sp_profileadmin_init(){
	try {
	if(isAdminTheme()){
	    $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
		drupal_add_js(drupal_get_path('module', 'exp_sp_core').'/js/exp_sp_profile/exp_sp_profilewidget.js', $js_module_optional);
	 	//drupal_add_js(drupal_get_path('module', 'exp_sp_core').'/js/exp_sp_profile/exp_sp_profile_tab.js', $js_module_optional);
	 	drupal_add_js(drupal_get_path('module', 'exp_sp_core').'/js/exp_sp_profile/exp_sp_profilemapwidget.js', $js_module_optional);
	 	drupal_add_js(drupal_get_path('module', 'exp_sp_core').'/js/exp_sp_profile/exp_sp_entityprofilewidget.js', $js_module_optional);
	}
	}catch (Exception $ex) {
		watchdog_exception('exp_sp_profileadmin_init', $ex);
		expertusErrorThrow($ex);
	}
}

function exp_sp_profileadmin_profileadmin(){
	try {
	$out  = "<div id='ProfileMasterService' class='rightBoxleftcorner' data=''>";
	$out .= "<div class='rightBoxrightcorner'><h2 style='float: left; color: #fff;'>&nbsp;&nbsp;Under Construction</h2></div>";
	$out .= "<div class='MainContentUnderConstructionDiv'>";
	$out .= "<span class='MainContentUnderConstructionTxt'>Under Construction</span>";
	$out .= "</div>";
	$out .= "</div>";
	return $out;
	}catch (Exception $ex) {
		watchdog_exception('exp_sp_profileadmin_profileadmin', $ex);
		expertusErrorThrow($ex);
	}
}

function exp_sp_profileadmin_profile() {
	try {
  $out.="<div id='ProfileService'  class='profileadmin' data=''></div>";
  return $out;
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_profileadmin_profile', $ex);
  	expertusErrorThrow($ex);
  }
}

/**
 * Implementation of hook_permission().
 */
function exp_sp_profileadmin_permission() {
	try {
  return array(    
    'Profile Admin Perm' => array(
      'title' => t('Profile Admin Perm')
    )
  );
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_profileadmin_permission', $ex);
  	expertusErrorThrow($ex);
  }
} 

function exp_sp_profileadmin_catalogstatus(){
  try{
  $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
	drupal_add_js(drupal_get_path('module', 'exp_sp_learning_admin').'/js/exp_sp_catalogadmin/exp_sp_catalogwidget.js', $js_module_optional);
	drupal_add_js(drupal_get_path('module', 'exp_sp_learning_admin').'/js/exp_sp_catalogadmin/exp_sp_catalogitemwidget.js', $js_module_optional);
	global $user;
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("Catalog Status")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	$out.="<input type='hidden' id='catStatus' value='1'>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_catalogstatus', $ex);
    expertusErrorThrow($ex);
  } 
}


function exp_sp_profileadmin_catalogtype(){
  try{
	global $user;
	expDebug::dPrint("in catalogtype");
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("Catalog Type")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_catalogtype', $ex);
    expertusErrorThrow($ex);
  } 
}


function exp_sp_profileadmin_hrstatus(){
  try{
	global $user;
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("HR Status")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_hrstatus', $ex);
    expertusErrorThrow($ex);
  }
}

function exp_sp_profileadmin_hrtype(){
  try{
	global $user;
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("HR Type")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_hrtype', $ex);
    expertusErrorThrow($ex);
  }
}

function exp_sp_profileadmin_sysstatus(){
  try{
	global $user;
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("System Status")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	return $out;
   }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_sysstatus', $ex);
    expertusErrorThrow($ex);
  }
}

function exp_sp_profileadmin_systype(){
  try{
	global $user;
	$out="<div id='ProfileService'  class='profileadmin' data=''></div>";
	if(in_array("sys admin",$user->roles)){
		//show catalog status tree with read/write access
		$out.="<input type='hidden' id='profileAccess' value='111'>";
	} else {
		//show catalog status tree with read access
		$out.="<input type='hidden' id='profileAccess' value='000'>";
	}
	$out.="<input type='hidden' id='profileTitle' value='".t("System Type")."'>";
	$out.="<input type='hidden' id='profileType' value='1'>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileadmin_systype', $ex);
    expertusErrorThrow($ex);
  }
}

