<?php 
$testCases = array(

			// CreateSurveyQuestionAPI test case Starts
			'CreateSurveyQuestionAPI' => array(
				'datasource' => array(
					array('input'=>array('userid'=>1,
						  				 'survey_status'=>'sry_qtn_sts_atv',
										 'lang_code'=>'cre_sys_lng_eng',
										 'question_type'=>'sry_qtn_typ_dpn',
										 'question_txt'=>'Sample Question?',
									 	 'answers_list'=>'answ1@@answ2@@answ3'),
						  'output'=>array('id'),
						  'result'=>array('<results totalrecords =','<result>','<id>'),
						  'output_type'=>'xml'
						  ),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_dpn',
								'question_txt'=>'Overall experience with this course',
								'answers_list'=>'Excellent@@Good@@Fair@@Poor'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'The delivery method of this course (Classroom, Computer, Video) was effective way for me to learn this subject matter.',
								'answers_list'=>'Strongly Disagree@@Disagree@@Agree@@Strongly Agree'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'How much would you rate the content?(Where 5 being the highest)',
								'answers_list'=>'5@@4@@3@@2@@1'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'The knowledge and/or skills gained through this course are directly applicable to my job',
								'answers_list'=>'Strongly Disagree@@Disagree@@Agree@@Strongly Agree'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
				  	array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Please rate your level of interest in the topic',
								'answers_list'=>'Very high@@High@@Low@@Very Low@@Average'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'The instructor managed the class effectively',
								'answers_list'=>'Strongly Disagree@@Disagree@@Agree@@Strongly Agree'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Please rate the learning material used in this training and its ability to engage you.',
								'answers_list'=>'Excellent@@Good@@Average@@Poor@@Very Poor'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_yno',
								'question_txt'=>'I clearly understood the course objectives',
								'answers_list'=>'Yes@@No'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'How satisfied were you with Scheduling of the orientation',
								'answers_list'=>'Extremely Satisfied@@Satisfied@@Neutral@@Dissatisfied@@Extremely Dissatisfied'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Clarity and variety of presentations',
								'answers_list'=>'Extremely Satisfied@@Satisfied@@Neutral@@Dissatisfied@@Extremely Dissatisfied'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_yno',
								'question_txt'=>'Clear and understandable presentation of benefits package',
								'answers_list'=>'Yes@@No'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_yno',
								'question_txt'=>'Did you receive a copy of the employee handbook?',
								'answers_list'=>'Yes@@No'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'In terms of time, was the average session',
								'answers_list'=>'Too long@@Just right@@Too short@@Don’t know'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Please rate the Location where the class was conducted',
								'answers_list'=>'Excellent@@Good@@Average@@Poor@@Very Poor.'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Please rate the ability of the instructor to to effectively answer questions',
								'answers_list'=>'Excellent@@Good@@Average@@Poor@@Very Poor.'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Please rate the quality of the video used',
								'answers_list'=>'Excellent@@Good@@Average@@Poor@@Very Poor.'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'How much would you rate the content?(Where 5 being the highest)',
								'answers_list'=>'5@@4@@3@@2@@1'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
					array('input'=>array('userid'=>1,
								'survey_status'=>'sry_qtn_sts_atv',
								'lang_code'=>'cre_sys_lng_eng',
								'question_type'=>'sry_qtn_typ_rtg',
								'question_txt'=>'Based only on the content and material, could you confidently recommend to other students?',
								'answers_list'=>'Definitely@@Probably@@Maybe@@Probably not@@Definitely not'),
								'output'=>array('id'),
								'result'=>array('<results totalrecords =','<result>','<id>'),
								'output_type'=>'xml'
						),
				),
				'validate' => array(
					array(
						  'input'=>array('userid'=>1,
										 'survey_status'=>'',
										 'lang_code'=>'cre_sys_lng_eng',
									     'question_type'=>'sry_qtn_typ_dpn',
									     'question_txt'=>'Sample Question?',
										 'answers_list'=>'answ1@@answ2@@answ3'),
						  'output'=>array('id'),
						  'result'=>array('<error>','<error_code>','<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg>','survey_status'),
						  'output_type'=>'xml'
						  )
				 
				)
			),  // CreateSurveyQuestionAPI test case Ends
			
		); // End of api test case main array
?>