<?php 
$testCases = array(
		'CreateLocationAPI' => array(
				'datasource' => array(
						 array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'equipment'=>'lrn_res_eqm_com',
								'capacity'=>'50',
								'addr1' => 'kilpauk',
								'addr2' => 'chennai',
								'city'  => 'Mountain View' ,
								'state'  => 'CA',
								'country' => 'US',
								'zipcode'  => '123456789',
								//'latitude' => '',
								//'longitude' => '',
								'contact_fname'  => '1861',
								'phone' => '5',
								'email_id' => 'joolavasavi@email.com',
								'status'  => 'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_059',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						), 
						array('input'=>array('name'=>'Cleveland Ohio',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '1245325884',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'The Park',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '1245325884',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'Golden Tulip Hotel',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '1245325884',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'Waterloo Conference Room',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '1245325884',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'Sheraton Imperial Hotel',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '1245325884',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array('Id'),
								'result'=>array('<results totalrecords =','<Id>'),
								'output_type'=>'xml'
						)						
						),
						
				'validate' =>array(
						array('input'=>array('name'=>'',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '600010',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.zipcode'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'50',
								'city'=>'',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.city'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => '',
								'country' => 'US',
								'zipcode' => '',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.state'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => '',
								'zipcode' => '',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.country'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '600010',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.capacity'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'REST_API_Location_Title_VERSION',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '600010',
								'status' =>'',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<short_msg>Mandatory Fields are missing in the feed. List provided below:</short_msg><long_msg>1.status'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'Test Latitude',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '600010',
								'latitude' => '99999999999',
								'longitude' => '9999999999',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>1
						),
								'output'=>array(),
								'result'=>array('<error_code>5</error_code><short_msg>Invalid latitude/longitude.</short_msg>'),
								'output_type'=>'xml'
						),
						array('input'=>array('name'=>'Test Access',
								'capacity'=>'50',
								'city'=>'Mountain View',
								'state' => 'CA',
								'country' => 'US',
								'zipcode' => '600010',
								'status' =>'lrn_res_loc_atv',
								'timezone' => 'cre_sys_tmz_001',
								'userid' =>''
						),
								'output'=>array(),
								'result'=>array('<error_code>L_010</error_code><short_msg>INVALID ACCESS</short_msg><long_msg>Userid is invalid</long_msg>'),
								'output_type'=>'xml'
						),
		
				),
)
)


?>