<?php 

$testCases = array(

			// CreateDiscountAPI test case Starts
			'CreateDiscountAPI' => array(
				'datasource' => array(
					array('input'=>array('userid'=>1,
							             'name'=>'sadad',
							             'description'=>'sadad',
										 'type'=>'percentage_off',
										 'is_active'=>0,
										 'value'=>10,
										 'max_uses'=>10,
										 'min_price'=>10,
										 'max_uses_per_user'=>10,
										 'max_uses_per_code'=>10,
										 'code'=>'sadad',
										 'for_all_trainings'=>0,
										 'for_all_users'=>0,
										 'combine_with_others'=>1),
						  'output'=>array('id'),
						  'result'=>array('<results totalrecords =','<result>','<id>'),
						  'output_type'=>'xml'
							),
					array(
							'input'=>array(	'userid'=>1,
											'name'=>'Customer Discount',
											'description'=>'Customer Discount',
											'type'=>'percentage_off',
											'is_active'=>0,
											'value'=>10,
											'max_uses'=>100,
											'min_price'=>100,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'CUSTID',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							),
					array(
							'input'=>array(	'userid'=>1,
											'name'=>'Partner Discount',
											'description'=>'Partner Discount',
											'type'=>'percentage_off',
											'is_active'=>0,
											'value'=>20,
											'max_uses'=>100,
											'min_price'=>100,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'PARTID',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							),
					array(
							'input'=>array(	'userid'=>1,
											'name'=>'Employee Discount',
											'description'=>'Employee Discount',
											'type'=>'percentage_off',
											'is_active'=>0,
											'value'=>30,
											'max_uses'=>100,
											'min_price'=>100,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'EMPID',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							),
					array(	
							'input'=>array(	'userid'=>1,
											'currency_type' =>'GBP',
											'name'=>'GBP Discount',
											'description'=>'GBP Discount',
											'type'=>'Fixed amount off',
											'is_active'=>0,
											'value'=>10,
											'max_uses'=>100,
											'min_price'=>25,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'GBP',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							),
					array(
							'input'=>array(	'userid'=>1,
											'currency_type' =>'USD',
											'name'=>'USD Discount',
											'description'=>'USD Discount',
											'type'=>'Fixed amount off',
											'is_active'=>0,
											'value'=>10,
											'max_uses'=>100,
											'min_price'=>25,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'USD',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							),
					array(
							'input'=>array(	'userid'=>1,
											'currency_type' =>'EUR',
											'name'=>'GBP Discount',
											'description'=>'EUR Discount',
											'type'=>'Fixed amount off',
											'is_active'=>0,
											'value'=>10,
											'max_uses'=>100,
											'min_price'=>25,
											'max_uses_per_user'=>100,
											'max_uses_per_code'=>100,
											'code'=>'EUR',
											'for_all_trainings'=>1,
											'for_all_users'=>1,
											'combine_with_others'=>1),
							'output'=>array('id'),
							'result'=>array('<results totalrecords =','<result>','<id>'),
							'output_type'=>'xml'
							)
				),
				'validate' => array(
 				    array('input'=>array('userid'=>1,
							             'name'=>'sadad',
							             'description'=>'sadad',
										 'type'=>'percentage_off',
										 'is_active'=>0,
										 'value'=>10,
										 'max_uses'=>10,
										 'min_price'=>10,
										 'max_uses_per_user'=>10,
										 'max_uses_per_code'=>10,
										 'code'=>'sadad',
										 'for_all_trainings'=>0,
										 'for_all_users'=>0,
										 'combine_with_others'=>1),
						  'output'=>array('id'),
						 // 'result'=>array('<results totalrecords =','<result>','<id>Code already exists.</id>'),
 				    	  'result'=>array('<results totalrecords =','<result>','<id>'),
						  'output_type'=>'xml'
							),
					array(
						  'input'=>array('userid'=>1,
										 'name'=>'',
										 'description'=>'sadad',
										  'type'=>'percentage_off',
										 'is_active'=>0,
										 'value'=>10,
										 'max_uses'=>10,
										 'min_price'=>10,
										 'max_uses_per_user'=>10,
										 'max_uses_per_code'=>10,
										 'code'=>'sadad',
										 'for_all_trainings'=>0,
										 'for_all_users'=>0,
										 'combine_with_others'=>1),
						  'output'=>array('id'),
						  'result'=>array('<error>','<error_code','name'),
						  'output_type'=>'xml'
						),
					array(
						  'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
						  'output'=>array('id'),
						  'result'=>array('<error>','<error_code','description'),
						  'output_type'=>'xml'
						),
					array(
						  'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
						 'output'=>array('id'),
						 'result'=>array('<error>','<error_code','type'),
						 'output_type'=>'xml'
					),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>'',
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','is_active'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>'',
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','value'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>'',
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','max_uses'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>'',
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','min_price'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>'',
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','max_uses_per_user'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>'',
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','max_uses_per_code'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','code'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>'',
										'for_all_users'=>0,
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','for_all_trainings'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>'',
										'combine_with_others'=>1),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','for_all_users'),
								'output_type'=>'xml'
						),
						array(
								'input'=>array('userid'=>1,
										'name'=>'sadad',
										'description'=>'sadad',
										'type'=>'percentage_off',
										'is_active'=>0,
										'value'=>10,
										'max_uses'=>10,
										'min_price'=>10,
										'max_uses_per_user'=>10,
										'max_uses_per_code'=>10,
										'code'=>'sadad',
										'for_all_trainings'=>0,
										'for_all_users'=>0,
										'combine_with_others'=>''),
								'output'=>array('id'),
								'result'=>array('<error>','<error_code','combine_with_others'),
								'output_type'=>'xml'
						)
									)
			),  // CreateDiscountAPI test case Ends
			
		); // End of api test case main array
?>