<?php

/**
 * Generate a token for a piece of content.
 */
function nodejs_generate_content_token() {
  return drupal_hmac_base64(drupal_random_bytes(512), drupal_get_private_key() . drupal_get_hash_salt());
}

/**
 * Send a content change message to a content channel.
 */
function nodejs_send_content_channel_message($message) {
  Nodejs::sendContentTokenMessage($message);
}

/**
 * Send a content channel token to Node.js.
 *
 * @param mixed $channel
 * @param mixed $notify_on_disconnect
 */
function nodejs_send_content_channel_token($channel, $notify_on_disconnect = FALSE) {
  $message = (object) array(
    'token' => nodejs_generate_content_token(),
    'channel' => $channel,
    'notifyOnDisconnect' => $notify_on_disconnect,
  );

  $response = Nodejs::sendContentToken($message);
  if (isset($response->error)) {
    $args = array('%token' => $message->token, '%code' => $response->code, '%error' => $response->error);
    watchdog('nodejs', t('Error sending content token "%token" to the Node.js server: [%code] %error', $args));
    return FALSE;
  }

  // We always set this in drupal.settings, even though Ajax requests will not
  // see it. It's a bit ugly, but it means that setting the tokens for full
  // page requests will just work.
  drupal_add_js(array('nodejs' => array('contentTokens' => array($channel => $message->token))), array('type' => 'setting'));

  $response->token = $message->token;
  return $response;
}

/**
 * Get a list of users in a content channel.
 *
 * @param mixed $channel
 */
function nodejs_get_content_channel_users($channel) {
  $message = (object) array('channel' => $channel);
  $response = Nodejs::getContentTokenUsers($message);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error getting content channel users for channel "%channel". Node.js server said: [%code] %error', array('%channel' => $channel, '%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    $data = drupal_json_decode($response->data);
    return $data['users'];
  }
}

/**
 * Kick a user off the node.js server.
 *
 * @param mixed $uid
 */
function nodejs_kick_user($uid) {
  $response = Nodejs::kickUser($uid);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error kicking uid "%uid" from the Node.js server: [%code] %error', array('%uid' => $uid, '%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    return $response;
  }
}

/**
 * Logout any sockets associated with the given token from the node.js server.
 *
 * @param mixed $token
 */
function nodejs_logout_user($token, $uid, $username) {
  $response = Nodejs::logoutUser($token, $uid, $username);
  expDebug::dPrint('$response = ' . print_r($response, true), 4);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error logging out token "%token" from the Node.js server: [%code] %error', array('%token' => $token, '%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    return $response;
  }
}

/**
 * Set the list of uids a user can see presence notifications for.
 *
 * @param $uid
 * @param $uids
 */
function nodejs_set_user_presence_list($uid, array $uids) {
  $response = Nodejs::setUserPresenceList($uid, $uids);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error setting user presence list for uid "%uid", error from the Node.js server: [%code] %error', array('%uid' => $uid, '%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    return $response;
  }
}

/**
 * Broadcast a message to all clients.
 *
 * @param string $subject
 * @param string $body
 */
function nodejs_broadcast_message($subject, $body) {
  $message = (object) array(
    'broadcast' => TRUE,
    'data' => (object) array(
      'subject' => $subject,
      'body' => $body,
    ),
    'channel' => 'nodejs_notify',
  );
  nodejs_enqueue_message($message);
}

/**
 * Send a message to all users subscribed to a given channel.
 */
function nodejs_send_channel_message($channel, $subject, $body) {
  $message = (object) array(
    'data' => (object) array(
      'subject' => $subject,
      'body' => $body,
    ),
    'channel' => $channel,
  );
  nodejs_enqueue_message($message);
}

/**
 * Send a message to given user.
 *
 * @param int $uid
 * @param string $subject
 * @param string $body
 */
function nodejs_send_user_message($uid, $subject, $body) {
  $message = (object) array(
    'data' => (object) array(
      'subject' => $subject,
      'body' => $body,
    ),
    'channel' => 'nodejs_user_' . $uid,
    'callback' => 'nodejsNotify',
  );
  nodejs_enqueue_message($message);
}

/**
 * Send a message to multiple users.
 *
 * @param string|array $uids
 *   A list of uid seperated by comma (,) or an array of uids
 * @param string $subject
 * @param string $body
 */
function nodejs_send_user_message_multiple($uids, $subject, $body) {
  if (!is_array($uids)) {
    $uids = explode(',', $uids);
  }
  foreach ($uids as $uid) {
    nodejs_send_user_message($uid, $subject, $body);
  }
}

/**
 * Send a message to users in a role.
 *
 * @param string $role_name
 * @param string $subject
 * @param string $body
 */
function nodejs_send_role_message($role_name, $subject, $body) {
  $query = db_select('users', 'u');
  $query->join('users_roles', 'ur', 'ur.uid = u.uid');
  $query->join('role', 'r', 'ur.rid = r.rid');
  $uids = $query->fields('u',array('uid'))
            ->condition('r.name', $role_name)
            ->execute()
            ->fetchCol();
  nodejs_send_user_message_multiple($uids, $subject, $body);
}

/**
 * Implements hook_init().
 */
function nodejs_init() {
	global $user; // EXPERTUS - restricting drupalchat+nodejs for authenticated users only, added $user->uid > 0 check below in if stmt
  drupal_register_shutdown_function(array('Nodejs', 'sendMessages'));
  if ($user->uid > 0 && drupal_match_path(drupal_get_path_alias(), variable_get('nodejs_pages', '*'))) {
    $_SESSION['nodejs_config'] = $nodejs_config = nodejs_get_config();
    if (isset($nodejs_config['serviceKey'])) {
      unset($nodejs_config['serviceKey']);
    }
    $socket_io_config = nodejs_get_socketio_js_config($nodejs_config);
    expDebug::dPrint('$socket_io_config = ' . print_r($socket_io_config, true), 4);
    drupal_add_js($socket_io_config['path'], array('type' => $socket_io_config['type']));
    drupal_add_js(drupal_get_path('module', 'nodejs') . '/nodejs.js', array('type' => 'file'));
    drupal_add_js(array('nodejs' => $nodejs_config), array('type' => 'setting'));
    foreach (nodejs_get_js_handlers() as $handler_file) {
      drupal_add_js($handler_file, array('type' => 'file'));
    }
  }
}

/**
 * Return the path to the socket.io client js.
 */
function nodejs_get_socketio_js_config($nodejs_config) {
  $socket_io_config = array(
    'path' => variable_get('nodejs_socket_io_path', FALSE),
    'type' => variable_get('nodejs_socket_io_type', 'external'),
  );
  if (!$socket_io_config['path']) {
    $socket_io_config['path'] = $nodejs_config['scheme'] . '://' . $nodejs_config['host'] . ':'
                              . $nodejs_config['port'] . $nodejs_config['resource'] . '/socket.io.js';
  }
  return $socket_io_config;
}

/**
 * Get a list of javascript handler files.
 */
function nodejs_get_js_handlers() {
  $handlers = module_invoke_all('nodejs_handlers_info');
  drupal_alter('nodejs_js_handlers', $handlers);
  return $handlers;
}

/**
 * Implements hook_menu().
 */
function nodejs_menu() {
  return array(
    'admin/config/nodejs' => array(
      'title' => 'Nodejs',
      'description' => 'Configure nodejs module.',
      'position' => 'left',
      'weight' => -20,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
    ),
    'admin/config/nodejs/config' => array(
      'title' => 'Configuration',
      'description' => 'Adjust node.js settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('nodejs_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'nodejs.admin.inc',
    ),
    'nodejs/message' => array(
      'title' => 'Message from Node.js server',
      'page callback' => 'nodejs_message_handler',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'nodejs/user/channel/add' => array(
      'title' => 'Add a channel to the Node.js server',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('nodejs_add_user_to_channel_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Add a channel to the Node.js server.
 *
 * @param channel
 * @return boolean
 */
function nodejs_get_add_channel($channel) {
  $response = Nodejs::addChannel($channel);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error adding channel to the Node.js server: [%code] %error', array('%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    return TRUE;
  }
}

/**
 * Remove a channel from the Node.js server.
 *
 * @param channel
 * @return boolean
 */
function nodejs_get_remove_channel($channel) {
  $response = Nodejs::removeChannel($channel);
  if (isset($response->error)) {
    watchdog('nodejs', t('Error removing channel from the Node.js server: [%code] %error', array('%code' => $response->code, '%error' => $response->error)));
    return FALSE;
  }
  else {
    return TRUE;
  }
}

/**
 * Form callback, add a user to a channel.
 *
 * @param mixed $form
 * @param mixed $form_state
 * @return array
 */
function nodejs_add_user_to_channel_form($form, $form_state) {
  $form = array();
  $form['nodejs_uid'] = array(
    '#type' => 'textfield',
    '#description' => t('The user uid to add to a channel.'),
    '#title' => t('User uid to add'),
  );
  $form['nodejs_channel'] = array(
    '#type' => 'textfield',
    '#description' => t('The name of the channel to give a user access to.'),
    '#title' => t('Channel to add'),
  );
  $form['nodejs_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add user'),
  );
  return $form;
}

/**
 * Form submit callback - add a user to a channel on the Node.js server.
 *
 * @param mixed $form
 * @param mixed $form_state
 */
function nodejs_add_user_to_channel_form_submit($form, &$form_state) {
  $values = (object) $form_state['values'];
  if (nodejs_add_user_to_channel($values->nodejs_uid, $values->nodejs_channel)) {
    drupal_set_message(t("Added uid %uid to %channel.", array('%uid' => $values->nodejs_uid, '%channel' => $values->nodejs_channel)));
  }
  else {
    drupal_set_message(t("Failed to add uid %uid to %channel.", array('%uid' => $$values->nodejs_uid, '%channel' => $values->nodejs_channel)), 'error');
  }
}

/**
 * Form validate callback - add a user to a channel on the Node.js server.
 *
 * @param mixed $form
 * @param mixed $form_state
 * @return void
 */
function nodejs_add_user_to_channel_form_validate($form, &$form_state) {
  $values = (object) $form_state['values'];
  if (!preg_match('/^\d+$/', $values->nodejs_uid)) {
    form_set_error('nodejs_uid', t('Invalid uid - please enter a numeric uid.'));
  }
  if (!preg_match('/^([a-z0-9_]+)$/i', $values->nodejs_channel)) {
    form_set_error('nodejs_channel', t('Invalid channel name - only numbers, letters and underscores are allowed.'));
  }
}

/**
 * Enqueue a message for sending at the end of the request.
 *
 * @param StdClass $message
 */
function nodejs_enqueue_message(StdClass $message) {
	expDebug::dPrint('$message = ' . print_r($message, true), 4);
  $message->broadcast = isset($message->broadcast) ? $message->broadcast : FALSE;
  Nodejs::enqueueMessage($message);
}

/**
 * Send a message immediately.
 *
 * @param StdClass $message
 */
function nodejs_send_message(StdClass $message) {
  $message->broadcast = isset($message->broadcast) ? $message->broadcast : FALSE;
  return Nodejs::sendMessage($message);
}

/**
 * Implements hook_nodejs_user_channels().
 */
function nodejs_nodejs_user_channels($account) {
	//EXPERTUS mantis ticket #20389 - disabled nodejs_user channel by changing default value for variable nodejs_enable_userchannel
	//                                from TRUE to FALSE.
  if (variable_get('nodejs_enable_userchannel', FALSE) && $account->uid) {
    return array('nodejs_user_' . $account->uid);
  }
  return array();
}

/**
 * Implements hook_user_logout().
 */
function nodejs_user_logout($account) {
	expDebug::dPrint('$account = ' . print_r($account, true), 4);
	expDebug::dPrint('$_SESSION[nodejs_config] = ' . print_r($_SESSION['nodejs_config'], true), 4);
	$username = ($account->uid > 0)? $account->name : '';
  nodejs_logout_user($_SESSION['nodejs_config']['authToken'], $account->uid, $username);
}

/**
 * Check if the given service key is valid.
 */
function nodejs_is_valid_service_key($service_key) {
  return $service_key == variable_get('nodejs_service_key', '');
}

/**
 * Menu callback: handles all messages from Node.js server.
 */
function nodejs_message_handler() {
  if (!isset($_POST['messageJson'])) {
    drupal_json_output(array('error' => 'No message.'));
    drupal_exit();
  }

  $message = drupal_json_decode($_POST['messageJson']);
  expDebug::dPrint('$message = ' . print_r($message, true), 4);
  
  // EXPERTUS : Check moved down to after message is decoded, to be able to send
  //            error with clientId, so that inturn client could be informed
  if (!isset($_POST['serviceKey']) || !nodejs_is_valid_service_key($_POST['serviceKey'])) {
    drupal_json_output(array('error' => 'Invalid service key.', clientId => $message['clientId']));
    drupal_exit();
  }
  
  $response = array();
  switch ($message['messageType']) {
    case 'authenticate':
      $response = nodejs_auth_check($message);
      break;

    case 'userOffline':
      nodejs_user_set_offline($message['uid']);
      break;

    default:
      $handlers = array();
      foreach (module_implements('nodejs_message_callback') as $module) {
        $function = $module . '_nodejs_message_callback';
        $handlers += $function($message['messageType']);
      }
      foreach ($handlers as $callback) {
        $callback($message, $response);
      }
  }
  drupal_alter('nodejs_message_response', $response, $message);
  expDebug::dPrint('$response = ' . print_r($response, true), 4);
  drupal_json_output($response ? $response : array('error' => 'Not implemented', clientId => $message['clientId']));
  drupal_exit();
}

/**
 * Checks the given key to see if it matches a valid session.
 */
function nodejs_auth_check($message) {
	expDebug::dPrint('$message = ' . print_r($message, true), 4);
  $nodejs_auth_check_callback = variable_get('nodejs_auth_check_callback', 'nodejs_auth_check_callback');
  if (!function_exists($nodejs_auth_check_callback)) {
    throw new Exception("No nodejs_auth_check callback found - looked for '$nodejs_auth_check_callback'.");
  }
  $uid = $nodejs_auth_check_callback($message['authToken']);
  $auth_user = $uid > 0 ? user_load($uid) : drupal_anonymous_user();
  $auth_user->authToken = $message['authToken'];
  $auth_user->nodejsValidAuthToken = $uid !== FALSE;
  $auth_user->clientId = $message['clientId'];
  $auth_user->visibleUserID = getUserIdforChat($uid);
  expDebug::dPrint("checking the user list".print_r($auth_user->visibleUserID,true),4);
  
  //Get Full name of the user
  $auth_user->fullname = getPersonFullName($uid,$auth_user->name);

  if ($auth_user->nodejsValidAuthToken) {
    // Get the list of channels I have access to.
    $auth_user->channels = array();
    foreach (module_implements('nodejs_user_channels') as $module) {
      $function = $module . '_nodejs_user_channels';
      expDebug::dPrint('$function = ' . print_r($function, true), 4);
      foreach ($function($auth_user) as $channel) {
        $auth_user->channels[] = $channel;
      }
    }

    // Get the list of users who can see presence notifications about me.
    $auth_user->presenceUids = array_unique(module_invoke_all('nodejs_user_presence_list', $auth_user));

    $nodejs_config = nodejs_get_config();
    $auth_user->serviceKey = $nodejs_config['serviceKey'];
    drupal_add_http_header('NodejsServiceKey', $nodejs_config['serviceKey']);
    drupal_alter('nodejs_auth_user', $auth_user);
    if ($auth_user->uid) {
      nodejs_user_set_online($auth_user->uid);
    }
    $auth_user->contentTokens = isset($message['contentTokens']) ? $message['contentTokens'] : array();
  }
  expDebug::dPrint('$auth_user = ' . print_r($auth_user, true), 4);
  return $auth_user;
}

/**
 * Default Node.js auth check callback implementation.
 */
function nodejs_auth_check_callback($auth_token) {
	// EXPERTUS : $authKeySource line below added.
	$authKeySource = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off'/* || $_SERVER['SERVER_PORT'] == 443*/)? 'ssid' : 'sid';
  return db_query('SELECT uid FROM {sessions} WHERE MD5(' . $authKeySource . ') = :auth_key', array(':auth_key' => $auth_token))->fetchField();
}

/**
 * Get an auth token for the current user.
 */
function nodejs_auth_get_token() {
  $nodejs_auth_get_token_callback = variable_get('nodejs_auth_get_token_callback', 'nodejs_auth_get_token_callback');
  if (!function_exists($nodejs_auth_get_token_callback)) {
    throw new Exception("Cannot proceed without a valid nodejs_auth_get_token callback - looked for '$nodejs_auth_get_token_callback'.");
  }
  return $nodejs_auth_get_token_callback();
}

/**
 * Default nodejs_auth_get_token() implementation.
 */
function nodejs_auth_get_token_callback() {
  return md5(session_id());
}

/**
 * Set the user as online.
 *
 * @param $uid
 */
function nodejs_user_set_online($uid) {
}

/**
 * Set the user as offline.
 *
 * @param $uid
 */
function nodejs_user_set_offline($uid) {
}

/**
 * Get nodejs server config.
 *
 * @return array
 */
function nodejs_get_config() {
  $defaults = array(
    'scheme' => variable_get('nodejs_server_scheme', 'http'),
    'secure' => variable_get('nodejs_server_scheme', 'http') == 'https' ? 1 : 0,
    'host' => variable_get('nodejs_server_host', 'localhost'),
    'port' => variable_get('nodejs_server_port', '8080'),
    'resource' => '/socket.io',
    'authToken' => md5(session_id()),
    'serviceKey' => variable_get('nodejs_service_key', ''),
    //'websocketSwfLocation' => base_path() . drupal_get_path('module', 'nodejs') . '/socket_io/socket.io/support/socket.io-client/lib/vendor/web-socket-js/WebSocketMain.swf', // Original line
    'websocketSwfLocation' => base_path() . drupal_get_path('module', 'nodejs') . '/node_modules/socket.io/node_modules/socket.io-client/lib/vendor/web-socket-js/WebSocketMain.swf',// EXPERTUS added line
    
    // EXPERTUS added - start
    'minInitialReconnectDelay' => (int) variable_get('nodejs_exp_min_initial_reconnect_delay', 500),
    'maxInitialReconnectDelay' => (int) variable_get('nodejs_exp_max_initial_reconnect_delay', 5000),
    'reconnectLimit' => (int) variable_get('nodejs_exp_max_reconnect_delay', 120000),
    'reconnectAttempts' => (int) variable_get('nodejs_exp_reconnect_attempts', 20),
    'pageUnloadDelay' => (int) variable_get('nodejs_exp_page_unload_delay', 10000),
    'authTimeout' => (int) variable_get('nodejs_exp_auth_timeout', 10000),
    'flashPolicyPort' => (int) variable_get('nodejs_flash_policy_port', 10843)
  // EXPERTUS added - end
  );
  
  return variable_get('nodejs_config', array()) + $defaults;
}

/**
 * Get the URL of a Node.js callback.
 *
 * @param array $config
 *   The result of nodejs_get_config().
 * @param string $callback
 *   The path to call on Node.js server (without leading /).
 * @return string
 */
function nodejs_get_url($config, $callback = '') {
  return $config['scheme'] . '://' . $config['host'] . ':' . $config['port'] . '/' . $callback;
}

/**
 * Remove a user from a channel.
 *
 * @param mixed $uid
 * @param mixed $channel
 * @return boolean
 */
function nodejs_remove_user_from_channel($uid, $channel) {
  $result = Nodejs::removeUserFromChannel($uid, $channel);
  if (isset($result->error)) {
    $params = array(
      '%uid' => $uid,
      '%channel' => $channel,
      '%code' => $result->code,
      '%error' => $result->error,
    );
    watchdog('nodejs', t('Error removing user %uid from channel %channel on Node.js server: [%code] %error', $params));
    return (object) array();
  }
  else {
    return TRUE;
  }
}

/**
 * Add a user to a channel.
 *
 * @param mixed $uid
 * @param mixed $channel
 * @return boolean
 */
function nodejs_add_user_to_channel($uid, $channel) {
  $result = Nodejs::addUserToChannel($uid, $channel);
  expDebug::dPrint('$result = ' . print_r($result, true), 4);
  if (isset($result->error)) {
    $params = array(
      '%uid' => $uid,
      '%channel' => $channel,
      '%code' => $result->code,
      '%error' => $result->error,
    );
    watchdog('nodejs', t('Error adding user %uid to channel %channel on Node.js server: [%code] %error', $params));
    return (object) array();
  }
  else {
    return TRUE;
  }
}

/**
 * Get the client socket id associated with this request.
 */
function nodejs_get_client_socket_id() {
  $client_socket_id = isset($_POST['nodejs_client_socket_id']) ? $_POST['nodejs_client_socket_id'] : '';
  return preg_match('/^\d+$/', $client_socket_id) ? $client_socket_id : '';
}

class Nodejs {
  public static $messages = array();

  public static $config = NULL;

  public static $baseUrl = NULL;

  public static $headers = NULL;

  public static function initConfig() {
    if (!isset(self::$config)) {
      self::$config = nodejs_get_config();
      self::$headers = array('NodejsServiceKey' => self::$config['serviceKey']);
      self::$baseUrl = nodejs_get_url(self::$config);
    }
  }

  public static function getMessages() {
    return self::$messages;
  }

  public static function enqueueMessage(StdClass $message) {
  	expDebug::dPrint('self::$messages = ' . print_r(self::$messages, true), 4);
    self::$messages[] = $message;
  }

  public static function sendMessages() {
    foreach (self::$messages as $message) {
      self::sendMessage($message);
    }
  }

  public static function sendMessage(StdClass $message) {
    self::initConfig();
    drupal_alter('nodejs_message', $message);
    $message->clientSocketId = nodejs_get_client_socket_id();
    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode($message),
      'headers' => self::$headers,
    );
    expDebug::dPrint('publishUrl = ' . self::$baseUrl . 'nodejs/publish', 4);
    expDebug::dPrint('$options = ' . print_r($options, true), 4);
    return drupal_http_request(self::$baseUrl . 'nodejs/publish', $options);
  }

  public static function setUserPresenceList($uid, array $uids) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/user/presence-list/$uid/" . implode(',', $uids), array('headers' => self::$headers));
  }

  public static function logoutUser($token, $uid, $uname) {
    self::initConfig();
    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode(array('authToken' => $token, 'uid' => $uid, 'name' => $uname)),
      'headers' => self::$headers
    );    
    return drupal_http_request(self::$baseUrl . "nodejs/user/logout", $options);
  }

  public static function sendContentTokenMessage($message) {
    self::initConfig();
    $message->clientSocketId = nodejs_get_client_socket_id();
    drupal_alter('nodejs_content_channel_message', $message);
    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode($message),
      'headers' => self::$headers,
      'options' => array('timeout' => 5.0),
    );
    return drupal_http_request(self::$baseUrl . 'nodejs/content/token/message', $options);
  }

  public static function sendContentToken($message) {
    self::initConfig();
    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode($message),
      'headers' => self::$headers,
    );
    return drupal_http_request(self::$baseUrl . 'nodejs/content/token', $options);
  }

  public static function getContentTokenUsers($message) {
    self::initConfig();
    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode($message),
      'headers' => self::$headers,
    );
    return drupal_http_request(self::$baseUrl . 'nodejs/content/token/users', $options);
  }

  public static function kickUser($uid) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/user/kick/$uid", array('headers' => self::$headers));
  }

  public static function addUserToChannel($uid, $channel) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/user/channel/add/$channel/$uid", array('headers' => self::$headers));
  }

  public static function removeUserFromChannel($uid, $channel) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/user/channel/remove/$channel/$uid", array('headers' => self::$headers));
  }

  public static function addChannel($channel) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/channel/add/$channel", array('headers' => self::$headers));
  }

  public static function removeChannel($channel) {
    self::initConfig();
    return drupal_http_request(self::$baseUrl . "nodejs/channel/remove/$channel", array('headers' => self::$headers));
  }
}

