<?php
function exp_sp_profileconfig_profile() {
  try{
	drupal_add_js(drupal_get_path('module', 'exp_sp_core').'/js/exp_sp_profile/exp_sp_profileconfigwidget.js', array('type' => 'file', 'group' => JS_DEFAULT));
	$out.="<div id='ProfileConfigService'  class='profileconfig' data=''></div>";
	return $out;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_profileconfig_profile', $ex);
    expertusErrorThrow($ex);
  }
}

/**
 * Implementation of hook_permission().
 */
function exp_sp_profileconfig_permission() {
	try {
  return array(    
    'Profile Config Admin Perm' => array(
      'title' => t('Profile Config Admin Perm')
    )
  );
  }catch (Exception $ex) {
  	watchdog_exception('exp_sp_profileconfig_permission', $ex);
  	expertusErrorThrow($ex);
  }
}
?>