<?php
function exp_sp_administration_config_init(){
	if(arg(1)=='sitesetup' && arg(2)=='config'){
		global $theme_key;
		$css_theme_optional = array('type' => 'file', 'group' => CSS_THEME, 'weight'=>1300);
		if($theme_key == 'expertusoneV2') {
			//NEWUI THEME STYLE SHEET
			drupal_add_css(drupal_get_path('module', 'exp_sp_administration_config') .'/exp_sp_administration_config_v2.css', array('type' => 'file', 'group' => CSS_THEME, 'weight'=>1300));
		} else {
			drupal_add_css(drupal_get_path('module', 'exp_sp_administration_config') .'/exp_sp_administration_config.css', $css_theme_optional);
		}
	}
}

/* Implementation of hook_menu().
 */
function exp_sp_administration_config_menu() {
try{
  $items = array();

    $items['administration/sitesetup/config'] = array(
			    'title' => t('LBL1264'),
			    'page callback' => 'empty_value',
			    'access callback' => 'is_drupal_super_admin',
			    'access arguments' => array('Config Admin Perm'),
			    'type' => MENU_CALLBACK
    );
    $items['administration/sitesetup/config/search/all'] = array(
    		'title' => 'Fetch module list to display in JQGrid',
    		'page callback' => 'sendConfigListToJqGrid',
    		'access callback' => 'user_access',
    		'access arguments' => array('Config Admin Perm'),
    		'type' => MENU_CALLBACK,
    		'file' => 'exp_sp_administration_config.inc'
    );
    $items['administration/sitesetup/config/textfilter-autocomplete'] = array(
    		'title' => 'Search By Config Filter Autocomplete',
    		'page callback' => 'getConfigNameFilterAutoComplete',
    		'access callback' => 'user_access',
    		'access arguments' => array('Config Info Admin Perm'),
    		'type' => MENU_CALLBACK,
    		'file' => 'exp_sp_administration_config.inc',
    );
    $items['administration/sitesetup/config/group/%ctools_js'] = array(
	    		'title' => 'Edit Group',
	    		'page callback' => 'exp_sp_administration_group_display_addedit_form',
	    		'page arguments' => array(3,4),
	    		'access callback' => 'user_access',
	    		'access arguments' => array('Config Admin Perm'),
	    		'type' => MENU_CALLBACK,
	    		'file' => 'exp_sp_administration_config_group.inc'
    );
    /* Simbu - Currency */
    $items['administration/sitesetup/config/currency/%ctools_js'] = array(
    		'title' => 'Currency',
    		'page callback' => 'exp_sp_administration_currency_display_addedit_form',
    		'page arguments' => array(3,4),
    		'access callback' => 'user_access',
    		'access arguments' => array('Config Admin Perm'),
    		'type' => MENU_CALLBACK,
    		'file' => 'exp_sp_administration_config_currency.inc'
    );
    $items['administration/sitesetup/config/currency/add/%ctools_js'] = array(
    		'title' => 'Add Currency',
    		'page callback' => 'exp_sp_administration_addcurrency_display_addedit_form',
    		'page arguments' => array(3,4),
    		'access callback' => 'user_access',
    		'access arguments' => array('Config Admin Perm'),
    		'type' => MENU_CALLBACK,
    		'file' => 'exp_sp_administration_config_currency.inc'
    );
    $items['administration/sitesetup/config/currency/remove/%'] = array(
    		'title' => 'Remove Currency',
    		'page callback' => 'exp_sp_administration_removecurrency',
    		'page arguments' => array(5),
    		'access callback' => 'user_access',
    		'access arguments' => array('Config Admin Perm'),
    		'type' => MENU_CALLBACK,
    		'file' => 'exp_sp_administration_config_currency.inc'
    );
    /* Simbu - Currency */
	return $items;
	} catch (Exception $ex) {
		watchdog_exception('exp_sp_administration_config_menu', $ex);
		expertusErrorThrow($ex);
	}
}

function exp_sp_administration_config_permission() {
	try{
    return array(
    'Config Admin Perm' => array(
      'title' => t('Config Admin Perm')
    )
  );
    } catch (Exception $ex) {
    	watchdog_exception('exp_sp_administration_config_permission', $ex);
    	expertusErrorThrow($ex);
    }
}
?>