<?php

/**
 * Implementation of hook_menu().
 */
function exp_sp_administration_commerce_menu() {
 try {
  	$items = array();

    $items['administration/commerce'] = array(
    'title' => t('Commerce'),
    'page callback' => 'empty_value',
    'access callback' => 'user_access',
    'access arguments' => array('Commerce Administer Perm'),
    'type' => MENU_CALLBACK
    );
 
	return $items;
	}catch (Exception $ex) {
		watchdog_exception('exp_sp_administration_commerce_menu', $ex);
		expertusErrorThrow($ex);
	}
}

function exp_sp_administration_commerce_permission() {
	try {
    return array(    
    'Commerce Administer Perm' => array(
      'title' => t('Commerce Administer Perm')
    )
  );
    }catch (Exception $ex) {
    	watchdog_exception('exp_sp_administration_commerce_permission', $ex);
    	expertusErrorThrow($ex);
    }
} 
?>