<?php
/**
 * Implementation of hook_block_info().
 */
function exp_sp_learning_plan_detail_block_info() {
  try{
  $blocks = array();
 
  $blocks['learning_details'] = array(
    'info' => t('Learning Plan Details'),
  	'cache' => DRUPAL_CACHE_PER_ROLE,  
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'learning/learning-plan-details/*'
  );
  return $blocks;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_learning_plan_detail_block_info', $ex);
    expertusErrorThrow($ex);
  } 
}

/**
 * Implementation of hook_block_view().
 */
function exp_sp_learning_plan_detail_block_view($delta = ''){
  try{
   
  $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
  $css_module_optional = array('type' => 'file', 'group' => CSS_DEFAULT);
  $header_optional = array('type' => 'file', 'scope' => 'header', 'group' => JS_LIBRARY);
  $css_theme_optional = array('type' => 'file', 'group' => CSS_THEME);
  global $theme_key, $user; 
  
  require_once('exp_sp_learning_plan_detail.inc');
  $block = array();
  switch ($delta) {
    case 'learning_details':
      //include forum js
    	drupal_add_js(drupal_get_path('module', 'exp_sp_lnrsearch') .'/jquery.cookie.js', $js_module_optional);
      drupal_add_js(drupal_get_path('module', 'exp_sp_forum').'/exp_sp_forum.js',$js_module_optional);
      drupal_add_js(drupal_get_path('module', 'exp_sp_learning_plan_detail').'/exp_sp_learning_plan_detail.js',$js_module_optional);
      drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/exp_sp_progressbar.js', $js_module_optional);
      //drupal_add_js(drupal_get_path('module', 'exp_sp_my_profile') .'/exp_sp_my_profile.js',$js_module_optional);
      //drupal_add_js(drupal_get_path('module', 'exp_sp_my_skill') .'/exp_sp_my_skill.js',$js_module_optional);
      //drupal_add_js(drupal_get_path('module', 'exp_sp_my_activity') .'/exp_sp_my_activity.js',$js_module_optional);
      drupal_add_js(drupal_get_path('module', 'drupalchat') . '/js/jquery.mousewheel.js');
      includeJqGridJsCss();
      //include forum css
      if($theme_key == 'expertusoneV2') {
         drupal_add_css(drupal_get_path('module', 'exp_sp_forum') .'/exp_sp_forum_v2.css', array('type' => 'file', 'group' => CSS_THEME, 'weight'=>1300));
         drupal_add_css(drupal_get_path('module', 'exp_sp_learning_plan_detail').'/exp_sp_learning_plan_detail_v2.css', $css_module_optional);
         drupal_add_css(drupal_get_path('module', 'exp_sp_prerequisite') .'/exp_sp_prerequisite_v2.css', $css_theme_optional);
         //Add onclick register
         if (contentPlayerIsActive()) { // Based on a content player activation load the needed files.
         	drupal_add_css(drupal_get_path('module', 'exp_sp_survey').'/exp_sp_survey_learner/css/Survey_formatter_cp.css',$css_theme_optional);
         	drupal_add_css(drupal_get_path('module', 'exp_sp_learning_learner') .'/css/exp_sp_lnrenrollment_cp.css', $css_module_optional);
         } else {
         	drupal_add_css(drupal_get_path('module', 'exp_sp_learning_learner') .'/css/exp_sp_lnrenrollment_v2.css', $css_module_optional);
         }
         //drupal_add_css(drupal_get_path('module', 'exp_sp_my_profile') .'/exp_sp_my_profile_v2.css', $css_theme_optional);
         //drupal_add_css(drupal_get_path('module', 'exp_sp_my_activity') .'/exp_sp_my_activity_v2.css', array('type' => 'file', 'group' => CSS_DEFAULT));
         //drupal_add_css(drupal_get_path('module','exp_sp_my_skill') .'/exp_sp_my_skill_v2.css', array('type' => 'file', 'group' => CSS_DEFAULT));
      }else{
        drupal_add_css(drupal_get_path('module', 'exp_sp_forum') .'/exp_sp_forum.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_learning_plan_detail').'/exp_sp_learning_plan_detail.css', $css_module_optional); 
        //drupal_add_css(drupal_get_path('module', 'exp_sp_my_profile') .'/exp_sp_my_profile.css', $css_theme_optional);
        //drupal_add_css(drupal_get_path('module', 'exp_sp_my_activity') .'/exp_sp_my_activity.css', array('type' => 'file', 'group' => CSS_DEFAULT));
        //drupal_add_css(drupal_get_path('module','exp_sp_my_skill') .'/exp_sp_my_skill.css', array('type' => 'file', 'group' => CSS_DEFAULT)); 
      }
      enableCtool();
      $sendArg = (arg(0) == 'home' || arg(0) == 'share') ? arg(3) : arg(2);
      $learning_details = getlearning_DetailsInfo($sendArg);

      /*-- Check the access enabled and view the page --*/
      include_once(drupal_get_path('module', 'exp_sp_administration_catalog_access') .'/exp_sp_administration_catalog_access.inc');
      $isAccessEnabled = getEntityAccess($sendArg, $learning_details['learning'][0]->object_type);
      if ($user->uid == 0 && $isAccessEnabled) {
       $viewDetailPage = false;
      } else {
       $viewDetailPage = true;
       if($isAccessEnabled) {
        $userId = getSltpersonUserId();
        $isGroupMember = checkUserEntityAccess($sendArg, $learning_details['learning'][0]->object_type, $userId);
       } else {
        $isGroupMember = true;
       }
      }
      expDebug::dPrint( 'tp opbject type : ' . print_r($learning_details,1),4);
      $block['subject'] = $learning_details['learning'][0]->title;
      $block['content'] = " ";
       if ($viewDetailPage && $isGroupMember) {
      // $block['results'] = $learning_details;
      $learning_details = getFullLearningPlanDetails($learning_details);
      $block['results']['details'] = $learning_details;
	  /*if(arg(0) == 'share')
       $block['results']['attachments'] = getAttachmentsInfo(arg(3),'trainingplan'); 
       else 
       $block['results']['attachments'] = getAttachmentsInfo(arg(2),'trainingplan'); //Added by BalaG(19/12/2011) -- For TP Attachments Display */
       
       $additional = array (
       		"course_id" 		=> $learning_details->program_id,
       		"delivery_type" 	=> $learning_details->delivery_type_code,
       		"preRequiste"		=> $learning_details->preRequiste,
       		'additional_info'	=> $learning_details->additional_info,
       );
       $block['results']['miscContent'] = getEntityMiscDetails($learning_details->program_id,'trainingplan',$additional);
       // retrieving taxonomy term data id
       $block['results']['discussions'] = GetForumTopicListForDetail('learningplan',$learning_details->program_id);//Added for displaying discussions under training plan
      }
       break;
  }
  return $block;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_learning_plan_detail_block_view', $ex);
    expertusErrorThrow($ex);
  } 
}

/**
 * Implementation of hook_menu().
 */
function exp_sp_learning_plan_detail_menu($delta = ''){
  try{
    $items = array();
    $items['learning/learning-action-item/%'] = array (
		'title' => 'Fetch the list of courses for the learning plan details',
		'page callback' => 'callback_fetch_learning_action_item',
	    'page arguments' => array(2),
		'type' => MENU_CALLBACK,
	    'access arguments' => array('access content'),
		'file' => 'exp_sp_learning_plan_detail.inc'
	); 
	
    $items['learning/learning-classes-list/%'] = array (
		'title' => 'Fetch the list of classes for the course with basic details',
		'page callback' => 'fetch_classes_list',
	    'page arguments' => array(2,'',TRUE),
		'type' => MENU_CALLBACK,
	    'access arguments' => array('access content'),
		'file' => 'exp_sp_coursedetail.inc',
		'file path' => drupal_get_path('module', 'exp_sp_coursedetail'),
	);
    
    $items['learning/learning-detailed-classes-list/%'] = array (
    		'title' => 'Fetch the list of classes for the course with basic details',
    		'page callback' => 'fetch_detailed_class_list',
    		'page arguments' => array(2,'',TRUE),
    		'type' => MENU_CALLBACK,
    		'access arguments' => array('access content'),
    		'file' => 'exp_sp_coursedetail.inc',
    		'file path' => drupal_get_path('module', 'exp_sp_coursedetail'),
    );
    
    $items['learning/learning-detailed-courses-list/%'] = array (
    		'title' => 'Fetch the list of classes for the course with basic details',
    		'page callback' => 'fetch_detailed_courses_list',
    		'page arguments' => array(2,TRUE),
    		'type' => MENU_CALLBACK,
    		'access arguments' => array('access content'),
    		'file' => 'exp_sp_learning_plan_detail.inc',
    		//'file path' => drupal_get_path('module', 'exp_sp_coursedetail'),
    );
    
    $items['learning/learning-class-details/%'] = array (
		'title' => 'Fetch the details of a class',
		'page callback' => 'callback_fetch_learning_course_details',
	    'page arguments' => array(2),
		'type' => MENU_CALLBACK,
	    'access arguments' => array('access content'),
		'file' => 'exp_sp_learning_plan_detail.inc'
	);
	$items['learning/learning-plan-details/%'] = array(
        'title' => 'COURSE / DELIVERY TYPE DETAILS',
        'page callback' => 'empty_value',
        'access arguments' => array('catalog learner'),
        'type' => MENU_CALLBACK,
    );
    $items['home/learning/learning-plan-details'] = array(
        'title' => 'COURSE / DELIVERY TYPE DETAILS',
        'page callback' => 'empty_value',
        'access arguments' => array('catalog learner'),
        'type' => MENU_CALLBACK,
    );
    
    $items['share/learning/learning-plan-details'] = array(
        'title' => 'COURSE / DELIVERY TYPE DETAILS',
        'page callback' => 'empty_value',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
	return $items;	
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_learning_plan_detail_menu', $ex);
    expertusErrorThrow($ex);
  } 
}

/**
 * Implementation of hook_theme().
 */
function exp_sp_learning_plan_detail_theme() {
  try{
  return array(
     'exp_sp_learning_plan_detail-view' => array (
      	'variables' => array('results' => array()),
      	'template' => 'exp_sp_learning_plan_detail-view',
	 ),
  );
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_learning_plan_detail_theme', $ex);
    expertusErrorThrow($ex);
  } 
}

/**
 * Implementation of class details callback.
 */
function callback_fetch_learning_course_details($classIdAndSessionId) {
  try{
  include DRUPAL_ROOT . "/sites/all/modules/core/exp_sp_learning/exp_sp_learning_learner/modules/exp_sp_coursedetail/exp_sp_coursedetail.inc";
  echo theme("exp_sp_learning_plan_detail-view", array('results' => fetch_class_details($classIdAndSessionId)));
  }catch (Exception $ex) {
    watchdog_exception('callback_fetch_learning_course_details', $ex);
    expertusErrorThrow($ex);
  }
}
function callback_fetch_learning_action_item() {  
  try{
  echo commonLPRegisterHtml(fetchLearningActionItem(arg(2)),true);
  }catch (Exception $ex) {
    watchdog_exception('callback_fetch_learning_action_item', $ex);
    expertusErrorThrow($ex);
  }
}