<?php
// $Id: uc_termsofservice.module,v 1.1.2.9 2010/07/17 15:17:46 pcambra Exp $

/**
 * Implementation of hook_uc_checkout_pane().
 */
function uc_termsofservice_uc_checkout_pane() {
  $title = t('Terms of Service');  
  $panes['uc_termsofservice_agreement_checkout'] = array(
    'enabled' => TRUE,
    'callback' => 'uc_termsofservice_checkout_pane_callback',
    'title' => t('@title', array('@title' => $title)),
    'desc' => t("Please confirm if you agree with our terms and conditions that apply on all our purchases."),
    'weight' => 6,
    'collapsible' => TRUE,
  );
  
  expDebug::dPrint('$_SERVER[REQUEST_URI] = ' . $_SERVER['REQUEST_URI'], 5);
  if (substr($_SERVER['REQUEST_URI'], -strlen('cart/checkout/paymethod')) == 'cart/checkout/paymethod' ||
         substr($_SERVER['REQUEST_URI'], -strlen('cart/checkout/review')) == 'cart/checkout/review')
    return $panes;
  else
    return;
}

/**
 * General form for both checkout & cart modes
 */
function uc_termsofservice_general_form($form_state, $type = NULL) {
	global $language; global $theme_key;
	expDebug::dPrint('$language = ' . print_r($language, true), 5);

	$vFilePath = getAdminSiteUrl().'/sites/default/files/terms_policy/';
	$filePathOnServer = $_SERVER['DOCUMENT_ROOT'].'/sites/default/files/terms_policy/'.'Terms_and_Conditions_' . $language->language . '.pdf';
	if (empty($language->language) || !file_exists($filePathOnServer)) {
    	$vPdfPathTerms = 'Terms_and_Conditions_en-us.pdf';
	}
	else {
		$vPdfPathTerms = 'Terms_and_Conditions_' . $language->language . '.pdf';
	}
  $form = array();
	
  if($theme_key == 'expertusoneV2'){
      $form['add-terms-and-conditons'] = array(
      '#type'   => 'markup',
      '#markup' => '<div style="float:left; width:100%">',
    );
      $attributes['onclick'][] = 'checkboxSelectedUnselectedCommon(this);';
      $form['tos_agree_terms'] = array(
    	'#prefix' => '<div class="checkbox-unselected">',
        '#suffix' => '</div>',
	    '#type' => 'checkboxes',
	    '#options' => array('agreed' => t("MSG477")), //I agree to Terms and Conditions.
        '#attributes' => $attributes,
	  );    
  }else{
       $form['tos_agree_terms'] = array(
    	'#prefix' => '<div style="float:left; width:100%">',
	    '#type' => 'checkboxes',
	    '#options' => array('agreed' => t("MSG477")), //I agree to Terms and Conditions.
	   );
  }	
  $form['conditioncontent'] = array(
    '#markup' => '<div id="cart_reg_condition">&nbsp;<a href="javascript:void(0)" onclick=\'window.open("'.$vFilePath.$vPdfPathTerms.'", "ExpertusONE", "width=1050, height=900,scrollbars=1 "); return false;\'>'.
                        t('LBL816') . '</a></div>', //View
    '#suffix' => '</div>'
  );
     
  return $form;
}

/**
 * Callback form for checkout pane.
 */
function uc_termsofservice_checkout_pane_callback($op) {
  switch ($op) {
    case 'view':      
        $form = uc_termsofservice_general_form(array(), 'checkout');
        return array('contents' => $form);
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function uc_termsofservice_form_alter(&$form, $form_state, $form_id) {  
  if ($form_id == 'uc_cart_checkout_exp_paymethod_form') {
  	expDebug::dPrint('modifying form uc_cart_checkout_review_form in uc_termsofservice_form_alter()', 5);
    $form['#validate'][] = 'uc_termsofservice_checkout_form_validate';
    expDebug::dPrint('$form = ' . print_r($form, true), 5);
    return;
  }
}

/**
 * Validate function for checkout, if required by config.
 * This way, we can display a better required message.
 */
function uc_termsofservice_checkout_form_validate($form, &$form_state) {
  expDebug::dPrint('$_SESSION[cart_order] = ' . $_SESSION['cart_order'], 5);
  expDebug::dPrint('$form_state[values] = ' . print_r($form_state['values'], true), 5);
  expDebug::dPrint('$form_state[storage] = ' . print_r($form_state['storage'], true), 5);

  $required = variable_get('uc_termsofservice_checkout_required', 0);
  if ($required) {
    $popup = variable_get('uc_termsofservice_checkout_popup', 0);
    if (!$popup) {
      $agreed_terms = $form_state['values']['panes']['uc_termsofservice_agreement_checkout']['tos_agree_terms']['agreed'];
    }
    else {
      $agreed_terms = $form_state['values']['panes']['uc_termsofservice_agreement_checkout']['tos_agree_terms_popup']['agreed'];
    }

	  if (!$agreed_terms) {
	    expDebug::dPrint('not agreed terms', 5);
	    form_set_error('tos_agree_terms', t('MSG482')); //You must agree to Terms and Conditions before purchasing.
	  }
  }
}
