<?php
/* Implementation of hook_menu().
 */
function exp_sp_administration_sitesetup_menu() {
try{
  $items = array();

    $items['administration/sitesetup'] = array(
    'title' => t('LBL1021'),
    'page callback' => 'empty_value',
    'access callback' => 'user_access',
    'access arguments' => array('Site Setup Admin Perm'),
    'type' => MENU_CALLBACK
    );
 
	return $items;
	} catch (Exception $ex) {
		watchdog_exception('exp_sp_administration_sitesetup_menu', $ex);
		expertusErrorThrow($ex);
	}
}

function exp_sp_administration_sitesetup_permission() {
	try{
    return array(    
    'Site Setup Admin Perm' => array(
      'title' => t('Site Setup Admin Perm')
    )
  );
    } catch (Exception $ex) {
    	watchdog_exception('exp_sp_administration_sitesetup_permission', $ex);
    	expertusErrorThrow($ex);
    }
} 
?>