<?php
/**
 * Implementation of hook_init().
 */
function exp_sp_administration_catalog_init() {
try {
        include_once(drupal_get_path('module', 'exp_sp_learning') .'/exp_sp_learning.inc');
      include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_class.inc');
      include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_course.inc');//51329
      include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_attachment.inc');  
      include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_session_details.inc');
      include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_content_details.inc');
      include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_class_register.inc');
      include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster.inc');
        global $theme_key;
        //$js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
        drupal_add_js(drupal_get_path('module', 'exp_sp_administration_user') .'/exp_sp_administration_user_addedit_behaviours.js', $js_module_optional);
      if($theme_key == 'expertusoneV2') {
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster_v2.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_v2.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_data_grid_v2.css', $css_theme_optional);
        
        if(module_exists('exp_sp_administration_customattribute')){   //#custom_attribute_0078975 - Check module status
            drupal_add_css(drupal_get_path('module', 'exp_sp_administration_customattribute') .'/exp_sp_administration_customattribute_v2.css', $css_theme_optional);
        } //#custom_attribute_0078975 - End Check module status
        
        if(stripos(request_uri(),'administration')!==false){
            drupal_add_css(drupal_get_path('module', 'exp_sp_administration') .'/exp_sp_administration_view_v2.css', $css_theme_optional);
        }
      } else {
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_data_grid.css', $css_theme_optional);
        if(stripos(request_uri(),'administration/learning/catalog')!==false){
         drupal_add_css(drupal_get_path('module', 'exp_sp_administration') .'/exp_sp_administration_view.css', $css_theme_optional);
        }
      }
          //Added by Subin Rajan for ticket #76370
      if(isset($_POST['enrollment_upload_file'])){
              expDebug::dPrint("Upload files name-->>" .print_r($_FILES,true),5);
        include_once('exp_sp_administration_class_register.inc');
        $process = bulk_enrollment_upload();
                setcookie("bulk_enrollment_upload_message", $process,null,'','','','');
        drupal_goto('administration/learning/catalog');
      }
//    /$js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
    // drupal_add_js(drupal_get_path('module', 'exp_sp_administration_user') .'/exp_sp_administration_user_addedit_behaviours.js', $js_module_optional);
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_administration_catalog_init', $ex);
    expertusErrorThrow($ex);
  }
}
/*
 * Implementation of hook_theme
 */
function exp_sp_administration_catalog_theme() {
    try {
  return array(
    'exp_sp_administration_catalog_detail' => array('
        variables' => array('results' => array()),
        'template' => 'exp_sp_administration_catalog_detail' 
        ),
    );
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_administration_catalog_theme', $ex);
    expertusErrorThrow($ex);
  }
}


/**
 * Implementation of hook_menu().
 */
function exp_sp_administration_catalog_menu() {
 try {
  $items = array();
  /*
   $items['administration/learning/catalog'] = array(
    'title' => t('LBL257'),
    'page callback' => 'getCatalogTabContent',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),    
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc',
    'weight' => 1
    );
   */
  
  $items['administration/learning/catalog'] = array(
    'title' => t('LBL257'),
    'page callback' => 'empty_value', 
    'access callback' => 'user_access',
    'type' => MENU_CALLBACK,
    'weight' => 1,
    'access arguments' => array('Catalog Course Admin Perm'),
    );
    
  $items['administration/learning/catalog/search/all'] = array(
    'title' => 'Fetch Catalog List to display in JQGrid',
    'page callback' => 'sendCatalogListToJqGrid',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc'
    ); 

  $items['administration/learning/catalog/textfilter-autocomplete'] = array(
    'title' => 'Search By Text Filter Autocomplete',
    'page callback' => 'getCatalogAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc',
    );
  
  $items['administration/learning/catalog/location-autocomplete'] = array(
    'title' => 'Location Autocomplete',
    'page callback' => 'getAdminLocationAutoComplete', /* Added/changed by ganeshbabuv on Jan 11th 2016 for  Location Filter #66404 */
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file path' => drupal_get_path('module','exp_sp_administration'),
    'file' => 'exp_sp_administration.inc',
    );
    
  $items['administration/learning/catalog/class-location-autocomplete'] = array(
    'title' => 'Class Location Autocomplete',
    'page callback' => 'getClassLocation',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog_class.inc',
  );
    
  $items['administration/learning/catalog/instructor-autocomplete'] = array(
    'title' => 'Search by Instructor username Autocomplete',
    'page callback' => 'getUsernameAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    );

  $items['administration/learning/catalog/export'] = array(
    'title' => 'Catalog Search Results CSV Export',
    'page callback' => 'fetchCatalogAll',
    'page arguments' => array('CSV'),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc',
    );
     
  $items['administration/learning/catalog/print'] = array(
    'title' => 'Catalog Search Results CSV Export',
    'page callback' => 'fetchCatalogAll',
    'page arguments' => array('PDF'),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc',
    );     

   $items['administration/learning/course-class/%ctools_js/addedit'] = array(
    'title' => 'Course',
    'page callback' => 'exp_sp_administration_courseclass_addedit_form',
    'page arguments' => array(3,5,6,7),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog_course.inc'
    );     

   $items['administration/learning/course-class/roster/%/%/%'] = array(
    'title' => 'Launch Roster',
    'page callback' => 'launchRoster',
    'page arguments' => array(4, 5, 6),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
   'file' => 'exp_sp_administration_catalog_roster.inc'
    );    

   $items['administration/learning/course-class/roster/load-drop-down/%'] = array(
    'title' => 'Drop Down List Roster',
    'page callback' => 'getDropDownList',
    'page arguments' => array(5),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
   'file' => 'exp_sp_administration_catalog_roster.inc'
    );        

   $items['administration/learning/course-class/roster/update/%'] = array(
    'title' => 'Launch Roster',
    'page callback' => 'updateRoster',
    'page arguments' => array(5),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
   'file' => 'exp_sp_administration_catalog_roster.inc'
    );

  $items['administration/learning/catalog/tag-autocomplete'] = array(
    'title' => 'Tag Autocomplete',
    'page callback' => 'getTagnameAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK
  );

  //administration/learning/catalog/publish-and-unpublish
  $items['ajax/administration/learning/catalog/publish-and-unpublish/%/%/%'] = array (
    'title' => 'Publish Or Unpublish Course-Class for a user',
    'page callback' => 'publishOrUnpublishCourseClass',
    'page arguments' => array(5, 6, 7),
    'type' => MENU_CALLBACK,
    'access arguments' => array('Catalog Course Admin Perm'),
    'file' => 'exp_sp_administration_catalog.inc'
    );
    
  //administration/learning/catalog/publish-and-unpublish
  $items['ajax/administration/learning/catalog/show-catalog/%'] = array (
        'title' => 'Show in Catalog Confirmation Message',
        'page callback' => 'getCountforComlienceAccessClass',
        'page arguments' => array(5),
        'type' => MENU_CALLBACK,
        'access arguments' => array('Catalog Course Admin Perm'),
        'file' => 'exp_sp_administration_catalog.inc'
  );
  
  $items['administration/learning/catalog-course/tag-autocomplete'] = array(
    'title' => 'Tag Autocomplete',
    'page callback' => 'getCourseTagnameAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK
  );
  
  $items['administration/learning/catalog-class/tag-autocomplete'] = array(
    'title' => 'Tag Autocomplete',
    'page callback' => 'getClassTagnameAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK
  );
  
  $items['administration/catalog-tags/%/%/%/%'] = array(
    'title' => 'Course Tags',
    //'page callback' => 'catalog_role_access_form',
    'page callback' => 'tags_addedit_form',
    'page arguments' => array(2,3,4,5),
    'access callback' => 'user_access',
    'access arguments' => array('expertus learner'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_tags.inc',
    'file path' => drupal_get_path('module', 'exp_sp_administration_learning')
  );
  
  $items['administration/update-tags/%/%/%/%'] = array(
    'title' => 'Course Tags',
    //'page callback' => 'catalog_role_access_form',
    'page callback' => 'tags_update',
    'page arguments' => array(2,3,4,5,6),
    'access callback' => 'user_access',
    'access arguments' => array('Learning Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_tags.inc',
    'file path' => drupal_get_path('module', 'exp_sp_administration_learning')
  );
  
  $items['administration/class-addedit/%/%/%/%'] = array(
    'title' => 'Catalog Class AddEdit',
    'page callback' => 'class_addedit_display',
    'page arguments' => array(2,3,4,5),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,    
    'file' => 'exp_sp_administration_catalog_class.inc'
  );
  $items['administration/class-pagination/%/%/%'] = array(
    'title' => 'Catalog Class AddEdit',
    'page callback' => 'getClassDetailsResults',
    'page arguments' => array(2,3,4),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,    
    'file' => 'exp_sp_administration_catalog_class.inc'
  );

  $items['administration/class-cancel-window/%/%'] = array(
    'title' => 'Catalog Class Cancel',
    'page callback' => 'class_cancel_display',
    'page arguments' => array(2,3,4),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,    
    'file' => 'exp_sp_administration_catalog_class.inc'
  );

  $items['administration/learning/catalog-class/enrolleduser-autocomplete'] = array(
    'title' => 'EnrolledUser Autocomplete',
    'page callback' => 'getEnrolledUserAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK
  );
  
  $items['administration/learning/catalog-class/notenrolleduser-autocomplete'] = array(
    'title' => 'NotEnrolledUser Autocomplete',
    'page callback' => 'getNotEnrolledUserAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK
  );  

  $items['administration/learning/catalog-class/enrolledtpuser-autocomplete'] = array(
    'title' => 'EnrolledTPUser Autocomplete',
    'page callback' => 'getEnrolledTPUserAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
    'file' => 'exp_sp_administration_tp_register.inc'
  );

  $items['administration/learning/catalog-class/notenrolledtpuser-autocomplete'] = array(
    'title' => 'NotEnrolledTPUser Autocomplete',
    'page callback' => 'getNotEnrolledTPUserAutoComplete',
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
    'file' => 'exp_sp_administration_tp_register.inc'
  );

  $items['administration/catalogbusinessrule/%/%/%/%'] = array(
    'title' => 'Buissness Rule',
    'page callback' => 'exp_sp_administration_class_bussiness_rule_form',
    'page arguments' => array(2,3,4,5),
    'access callback' => 'user_access',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
    'file' => 'exp_sp_administration_business_rules.inc'
    
  );  
  
  $items['administration/learning/catalog/content-autocomplete'] = array(
    'title' => 'Content Autocomplete',
    'page callback' => 'getClassContentAutoComplete',
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog.inc',
    );

  $items['administration/learning/catalog/class-autocomplete/%'] = array(
    'title' => 'Class Autocomplete',
    'page callback' => 'getClassAutoComplete',
    'page arguments' => array(4),
    'access arguments' => array('Catalog Course Admin Perm'),
    'type' => MENU_CALLBACK,
    'file' => 'exp_sp_administration_catalog_class.inc',
    );
  $items['ajax/class-add-session/%/%/%/%/%/%'] = array(
    'title' => 'Add Session',
    'page callback' => 'getClassAddSessionDisplay',
    'page arguments' => array(2,3,4,5,6,7),
    'access arguments' => array('expertus learner'),    
    'type' => MENU_CALLBACK,
      'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
    'file' => 'exp_sp_administration_session_details.inc'
  );
  $items['administration/learning/catalog/view-screen/%'] = array(
        'title' => 'Get enrolled class/tp list for view screen',
        'page callback' => 'getEnrollmentsResultForViewScreen',
        'page arguments' => array(4),
        'access callback' => 'user_access',
        'access arguments' => array('Catalog Course Admin Perm'),
        'type' => MENU_CALLBACK,
      'file' => 'exp_sp_administration_learning.inc',
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
    
  );
  $items['administration/view-class/%ctools_js/addedit/%'] = array(
        'title' => 'View Class',
        'page callback' => 'exp_sp_administration_viewclass_addedit_form',
        'page arguments' => array(3,4),
        'access callback' => 'user_access',
        'access arguments' => array('Catalog Course Admin Perm'),
        'type' => MENU_CALLBACK,
        'file' => 'exp_sp_administration_catalog.inc'
  );
  $items['administration/view-course/%ctools_js/addedit/%'] = array(
        'title' => 'View Course',
        'page callback' => 'exp_sp_administration_viewcourse_addedit_form',
        'page arguments' => array(3,4),
        'access callback' => 'user_access',
        'access arguments' => array('Catalog Course Admin Perm'),
        'type' => MENU_CALLBACK,
        'file' => 'exp_sp_administration_catalog.inc'
  );
  $items['administration/view-classdetails/%'] = array(
        'title' => 'View Class in Course',
        'page callback' => 'getClassViewResults',
        'page arguments' => array(2),
        'access callback' => 'user_access',
        'access arguments' => array('Catalog Course Admin Perm'),
        'type' => MENU_CALLBACK,
        'file' => 'exp_sp_administration_catalog.inc'
  );
  $items['administration/view-classdetails/%'] = array(
        'title' => 'View Class in Course',
        'page callback' => 'getClassViewResults',
        'page arguments' => array(2),
        'access callback' => 'user_access',
        'access arguments' => array('Catalog Course Admin Perm'),
        'type' => MENU_CALLBACK,
        'file' => 'exp_sp_administration_catalog.inc'
  );
  $items['administration/session/allinstructor/%'] = array(
        'title' => 'Add Session',
        'page callback' => 'getInstructorForSession',
        'page arguments' => array(3),
        'access arguments' => array('expertus learner'),    
        'type' => MENU_CALLBACK,
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
        'file' => 'exp_sp_administration_session_details.inc'
  );
  $items['administration/session/allinstructor-autocomplete'] = array(
        'title' => 'Add Session',
        'page callback' => 'getInstructorForSessionautocomplete',
        'access arguments' => array('expertus learner'),
        'type' => MENU_CALLBACK,
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
        'file' => 'exp_sp_administration_session_details.inc'
  );
  $items['administration/session/allpresenter/%'] = array(
        'title' => 'Add Session',
        'page callback' => 'getPresenterAll',
        'page arguments' => array(3),
        'access arguments' => array('expertus learner'),
        'type' => MENU_CALLBACK,
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
        'file' => 'exp_sp_administration_session_details.inc'
  );
  
 /******************** For Web-Ex Feature *******************/
  
  $items['ajax/presenter/webex-credentials/%'] = array(
        'title' => 'Presenter Credentials Check',
        'page callback' => 'getPresenterCredentials',
        'page arguments' => array(3),
        'access arguments' => array('expertus learner'),
        //'access arguments' => TRUE,
        'type' => MENU_CALLBACK,
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
        'file' => 'exp_sp_administration_session_details.inc'
  );
  $items['ajax/class-presenter-check'] = array(
        'title' => 'Presenter Check',
        'page callback' => 'getPresenterDisplay',
        //'page arguments' => array(2,3,4,5,6,7),
        'access arguments' => array('expertus learner'),
        'type' => MENU_CALLBACK,
        'file path' => drupal_get_path('module', 'exp_sp_administration_learning'),
        'file' => 'exp_sp_administration_session_details.inc'
  ); 
  
  /******************** Web-Ex Feature Ends *******************/
  
  expDebug::dPrint(' $items = ' . print_r($items, true), 4);
  return $items;
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_administration_catalog_menu', $ex);
    expertusErrorThrow($ex);
  }
}

/*
 * exp_sp_administration_courseclass_addedit_form() - Multi-Form implementation for course / class
 */
function exp_sp_administration_courseclass_addedit_form($js = NULL, $courseId, $classId = 0, $displayMode = ''){
  try {
    //0033772: Code Re-Factoring - Home page - Remove unwanted JavaScript
    includeFiles();
    $catalog_style = array(
        'ctools-admin-course-class-addedit-scroll-wrapper' => array(
        'modalSize' => array(
        'width' => 860,
        'minHeight' => 380,
       ),
      'modalTheme' => 'ExpertusCToolsAdminCourseModalTheme',
    )
  );

  drupal_add_js($catalog_style, 'setting');
  
  if ($js) {   
    // Prepare the arguments list to be passed to $formState['build_info']['args'] of each form
    $argsList = array();
    
    $courseTitle = '';
    if (!empty($courseId)) {
      $argsList[] = $courseId;
      $argsList[] = $classId;
      
      $courseTitle = ' - '.titleController(' ', getCourseTitleDirect($courseId),65);
    }
    
    if(!empty($displayMode)){
      $argsList['display_mode'] = $displayMode;
    }
    
   // Prepare list of forms to be displayed in the modal
    $formIdList = array(
                        array('id' => 'exp_sp_administration_catalog_course_addedit_form', 'title' => (t('Course'))),
                        array('id' => 'exp_sp_administration_catalog_class_title_form', 'title' => t('LBL353'))
                        );
                        
    exp_ctools_modal_multi_ajaxonly_forms_display($formIdList, $argsList);
  }
  else {
    throw new Exception('exp_sp_administration_catalog.module: exp_sp_administration_courseclass_addedit_form() : nojs');
  }
  }catch (Exception $ex) {
    watchdog_exception('exp_sp_administration_courseclass_addedit_form', $ex);
    expertusErrorThrow($ex);
  }
} 

function exp_sp_administration_catalog_permission() {
    try {
    return array(    
    'Catalog Course Admin Perm' => array(
      'title' => t('Catalog Course Admin Perm')
    )
  );
    }catch (Exception $ex) {
        watchdog_exception('exp_sp_administration_catalog_permission', $ex);
        expertusErrorThrow($ex);
    }
} 
/*
 * function to load list of files needs to be included for the module.
 * */

 function includeFiles(){
    include_once(drupal_get_path('module', 'exp_sp_learning') .'/exp_sp_learning.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_course.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_class.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_attachment.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_survey.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_assessment.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_tags.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_prerequisite.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_equivalence.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_session_details.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_content_details.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_class_register.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_custom_fields.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_notification_insert.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_business_rules.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_catalog_access') .'/exp_sp_administration_catalog_access.inc');
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_notification.inc');
     
    $css_theme_optional = array('type' => 'file', 'group' => CSS_THEME);
  include_once(drupal_get_path('module', 'exp_sp_coursedetail') .'/exp_sp_coursedetail.inc');
     
    $css_theme_optional = array('type' => 'file', 'group' => CSS_THEME);
    $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
    drupal_add_js(drupal_get_path('module', 'exp_sp_administration') .'/exp_sp_administration_addedit_behaviours.js', $js_module_optional);
    drupal_add_js(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster.js', $js_module_optional);
// Data Grid
    drupal_add_js(drupal_get_path('module', 'exp_sp_coursedetail') .'/exp_sp_coursedetail.js', $js_module_optional);
    
    //Using the below veriable we can find current loaded theme name
    global $theme_key;
    if($theme_key == 'expertusoneV2') {
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster_v2.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_v2.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_data_grid_v2.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration') .'/exp_sp_administration_view_v2.css', $css_theme_optional);
        //drupal_add_css(drupal_get_path('module', 'exp_sp_coursedetail') .'/exp_sp_coursedetail_v2.css', $css_theme_optional);
    } else {
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog_roster.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_catalog') .'/exp_sp_administration_catalog.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_data_grid.css', $css_theme_optional);
        drupal_add_css(drupal_get_path('module', 'exp_sp_administration') .'/exp_sp_administration_view.css', $css_theme_optional);
    }
     
    
    // Data Grid
    drupal_add_js(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_data_grid.js', $js_module_optional);
 }
 
 function validateRosterEnrollmentDetails($form, &$form_state, $callFromAPI = 0){
    include_once(drupal_get_path('module', 'exp_sp_administration_learning') .'/exp_sp_administration_class_register.inc');
    validateRosterEnrollmentDetails_impl($form, $form_state, $callFromAPI = 0);     
 }
?>