<?php 
/**
 * Implemention of hook_init()
 */
function exp_sp_widget_init() {
 	 global $base_url;
 	 $current_path = arg(0) . '/' . arg(1);
	 if(checkWidgetCallback($current_path)){
	  	$_SESSION['widgetCallback'] = true;
	  	drupal_add_js(array('widget' => array('widgetCallback' =>  $_SESSION['widgetCallback'])), 'setting');
	 }else{
	 		drupal_add_js(array('widget' => array('widgetCallback' =>  false)), 'setting');
	 } 
}

/**
 * Implemetion of hook_menu
 */
function exp_sp_widget_menu() {
	$items = array();
	// learing catalog search page
	$items['widget/catalog-search'] = array(
   	'title' => 'Widget Catalog',
   	'page callback' => 'getWidgetCatalogSearch',
   	'access callback' => TRUE,
   	'type' => MENU_CALLBACK,
   	'file' => 'exp_sp_widget.inc',
	);
	// Class detail page
	$items['widget/class-details'] = array(
	  'title' => 'Widget Class Details',
	  'page callback' => 'getWidgetClassDetails',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
	  'file' => 'exp_sp_widget.inc',
	);
	// Course detail page
	$items['widget/course-details'] = array(
	  'title' => 'Widget Course Details',
	  'page callback' => 'getWidgetCourseDetails',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
	  'file' => 'exp_sp_widget.inc',
	);
	// LP detail page
	$items['widget/learning-plan-details'] = array(
	  'title' => 'Widget Learning Plan Details',
	  'page callback' => 'getWidgetLearningPlanDetails',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
	  'file' => 'exp_sp_widget.inc',
	);
	
	// my learning page	
	$items['widget/enrollment-search'] = array(
	  'title' => 'Search Catalog',
	  'page callback' => 'getWidgetEnrollmentSearch',
	  'page arguments' => array(),
	  'access arguments' => array('access content'),
	  'type' => MENU_CALLBACK,
	  'file' => 'exp_sp_widget.inc',
	);
	// register page
	$items['widget/register'] = array(
	  'title' => 'Register',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('ajax_userregister'),
	  'access callback' => array('user_is_anonymous'),
	  'type' => MENU_CALLBACK,
	  'weight' => 10,
	);
	$items['widget/reset-password'] = array(
	  'title' => 'Register',
	  'page callback' => 'get_widget_password_reset',
	  'access callback' => array('user_is_logged_in'),
	  'type' => MENU_CALLBACK,
	  'weight' => 10,
	);
	
	return $items;
}



/**
 * Implementaion of hook_preprocess_html
 */
function exp_sp_widget_preprocess_html(&$variables) {
 try {
   global $theme_key; 
    /*-- Include page widget css on widget callback menu's ---*/
   $current_path = arg(0) . '/' . arg(1);
   $js_module_optional = array('type' => 'file', 'group' => JS_DEFAULT);
   if(checkWidgetCallback($current_path)){
     if ($theme_key == 'expertusoneV2') {
     	drupal_add_css(drupal_get_path('theme', 'expertusoneV2') . '/expertusone-internals/css/page-widget.css' , array('type' => 'file', 'group' => CSS_THEME));
     	drupal_add_js(drupal_get_path('module', 'exp_sp_lnrreports') .'/jscrollbar/jquery.mousewheel.js', array('type' => 'file', 'group' => JS_DEFAULT));
     	drupal_add_js(drupal_get_path('module', 'exp_sp_lnrsearch') .'/exp_sp_lnrsearch.js', $js_module_optional);
     	if (contentPlayerIsActive()) { // Based on a content player activation load the needed files.
     		includeContentPlayerJsCss();
     		drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_lnrenrollment/exp_sp_lnrenrollment_cp.js', $js_module_optional);
     		drupal_add_js(drupal_get_path('module', 'exp_sp_survey').'/exp_sp_survey_learner/js/exp_sp_surveylearner/exp_sp_surveylearner_cp.js',$js_module_optional);
     		drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/exp_sp_launch_cp.js', $js_module_optional);
     		drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM-API-WRAPPER_cp.js', $js_module_optional);
     		drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM12-LMS-API_cp.js', $js_module_optional);
     		drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM2004-LMS-API_cp.js', $js_module_optional);
     		drupal_add_css(drupal_get_path('module', 'fivestar').'/css/fivestar_v2.css',$css_theme_optional);
     		drupal_add_css(drupal_get_path('module', 'exp_sp_survey').'/exp_sp_survey_learner/css/Survey_formatter_cp.css',$css_theme_optional);
     		drupal_add_css(drupal_get_path('module', 'exp_sp_learning_learner') .'/css/exp_sp_lnrenrollment_cp.css',$css_theme_optional);
     	}else{
	       drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/exp_sp_launch.js', $js_module_optional);
	       if(getConfigValue('wbt_content_launch_style') == 1) {
		  	 drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM-API-WRAPPER-MODAL.js', $js_module_optional);
		   } else {
		  	 drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM-API-WRAPPER.js', $js_module_optional);
		   }
	       drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM12-LMS-API.js', $js_module_optional);
	       drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_registrationdetail/SCORM2004-LMS-API.js', $js_module_optional);
	       drupal_add_js(drupal_get_path('module', 'exp_sp_learning_learner').'/js/exp_sp_lnrenrollment/exp_sp_lnrenrollment.js', $js_module_optional);
     	}
       drupal_add_css(drupal_get_path('module', 'exp_sp_learning_learner') .'/css/exp_sp_lnrenrollment_v2.css', $css_module_optional);
     } else {
      drupal_add_css(drupal_get_path('theme', 'expertusone') . '/expertusone-internals/css/page-widget.css' , array('type' => 'file', 'group' => CSS_THEME));
     } 
    }
  } catch (Exception $ex) {
   watchdog_exception('exp_sp_widget_preprocess_html', $ex);
   expertusErrorThrow($ex);
  }
}

/**
 * Implementaion of hook_preprocess_page
 */
function exp_sp_widget_preprocess_page(&$variables, $hook) {
 try {
   $current_path = arg(0) . '/' . arg(1);
   if (checkWidgetCallback($current_path)){
  	unset($page['sidebar_first'], $page['sidebar_second'], $page['header'], $page['footer']);
  	$variables['theme_hook_suggestions'][] = 'page__widget';
   }
 } catch (Exception $ex) {
  watchdog_exception('exp_sp_widget_preprocess_page', $ex);
  expertusErrorThrow($ex);
 }
}

/*	for 41991: UI issue in external web page ( Reset user password)	*/
function get_widget_password_reset() {
	enableCtool();
	drupal_add_css('.popups-container, .popups-container-newui { position: relative; } #show_expertus_message #message-container { margin: auto; width: 93%; } .reset-pass-btn-cont .admin-save-button-container { margin-right: 5px; }', 'inline');
	$outputString = '<div id="lnr-catalog-search"><div id="searchRecordsPaint" class="search-record-paint"><table id=paintContentResults></table></div><div id="pager" style="display:none;"></div></div>
	<div style="display: block;" id="no-records" style="display:none;"></div>
	<a onclick="getClickSignIn()" class="use-ajax ctools-modal-ctools-login-style" id="signin" html="1" href="/?q=ctools_ajax_sample/ajax/user_login"></a>
	<a title="Reset Password" id="resetPwdLink" class="use-ajax ctools-modal-ctools-widget-reset-style" html="1" href="/?q=ctools_ajax_sample/ajax/reset_password" style="display: none;">Reset Password</a>';
	return $outputString;
}