$(document).ready(function(){
	$(".collapse-block").click(function(){
		if($(this).hasClass("open-block"))
		{
			$(this).removeClass("open-block")
	                $(this).parent().parent().next().slideUp("slow");
		}
		else
		{
			$(this).addClass("open-block")
	        $(this).parent().parent().next().slideDown("slow");
		}
	});
});