<?php

/**
 * Implementation of hook_menu().
 */
function exp_sp_administration_manage_menu() {
	try{

  $items = array();

    $items['administration/manage'] = array(
    'title' => t('Manage'),
    'page callback' => 'empty_value',
    'access callback' => 'user_access',
    'access arguments' => array('Manage Admin Perm'),
    'type' => MENU_CALLBACK
    );
 
	return $items;
	} catch (Exception $ex) {
    	watchdog_exception('exp_sp_administration_manage_menu', $ex);
    	expertusErrorThrow($ex);
    }
}

function exp_sp_administration_manage_permission() {
	try {
    return array(    
    'Manage Admin Perm' => array(
      'title' => t('Manage Admin Perm')
    )
  );
    } catch (Exception $ex) {
    	watchdog_exception('exp_sp_administration_manage_permission', $ex);
    	expertusErrorThrow($ex);
    }
} 
?>